/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.EditoraDAO;

/**
 *
 * @author willi
 */
public class JanelaEditora extends javax.swing.JFrame {

    private final EditoraDAO editora = EditoraDAO.getDaoEditora();
    private final JanelaEditoras janelaEditoras = JanelaEditoras.getJanelaCadEditora();
    private static JanelaEditora janelaEditora;

    /**
     * Creates new form JanelaEditora
     */
    
    private JanelaEditora () {
        initComponents();
        editora.getConBD().inicializaTudo("marvelLogo.jpg", "Marvel Comics", lbImagem1, lbNome1);
        editora.getConBD().inicializaTudo("dcLogo.jpg", "DC Comics", lbImagem2, lbNome2);
        editora.getConBD().inicializaTudo("dynamite.jpg", "Dynamite Entertainment", lbImagem3, lbNome3);
    }

    public final static JanelaEditora getJanelaEditora() {
        if (janelaEditora ==  null) {
            janelaEditora = new JanelaEditora();
        }
        return janelaEditora;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImagem2 = new javax.swing.JLabel();
        lbImagem3 = new javax.swing.JLabel();
        lbImagem1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbNome1 = new javax.swing.JLabel();
        lbNome2 = new javax.swing.JLabel();
        lbNome3 = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbImagem2.setText("Imagem 2");

        lbImagem3.setText("Imagem 3");

        lbImagem1.setText("Imagem 1");

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("Editora de Quadrinhos");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel2.setText("Editoras de Quadrinho mais Famosas");

        lbNome1.setText("Editora 1");

        lbNome2.setText("Editora 2");

        lbNome3.setText("Editora 3");

        btAdicionar.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        btAdicionar.setText("Adicionar Editora");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        btExcluir.setText("Exclui Editora");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        btEditar.setText("Editar Editora");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btBuscar.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        btBuscar.setText("Buscar Editora");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btAdicionar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lbNome1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(lbImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(lbImagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(lbNome2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbNome3)))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNome1)
                    .addComponent(lbNome2)
                    .addComponent(lbNome3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btEditar)
                    .addComponent(btBuscar)
                    .addComponent(btExcluir))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        if (editora.getConBD().verificaConexao()) {
            janelaEditoras.zeraCampos();
            JanelaInicial.criaThread(janelaEditoras); editora.getConBD().setValidar(1);
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        if (editora.getConBD().verificaConexao()) {
            janelaEditoras.setId(editora.getConBD().buscador("Editora"));
            if (janelaEditoras.getId() < 1) {
                editora.getConBD().informativo("Nenhuma editora possui este número de identificação!!!");
            } else {
                if (editora.buscar(janelaEditoras.getId())) {
                    janelaEditoras.setCampos(janelaEditoras.getId());
                    editora.getConBD().setValidar(2);
                    JanelaInicial.criaThread(janelaEditoras);
                }
            }
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        if (editora.getConBD().verificaConexao()) {
            int id = editora.getConBD().buscador("Editora");
            if (id < 1) {
                editora.getConBD().informativo("Nenhuma editora possui este número de identificação!!!");
            } else {
                if (editora.buscar(id)) {
                    janelaEditoras.setCampos(id);
                    editora.getConBD().setValidar(3);
                    JanelaInicial.criaThread(janelaEditoras);
                }
            }
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (editora.getConBD().verificaConexao()) {
            int id = editora.getConBD().buscador("Editora");
            if (id < 1) {
                editora.getConBD().informativo("Nenhuma editora possui este número de identificação!!!");
            } else {
                if (editora.excluir(id)) {
                    editora.getConBD().mensagens(3);
                    janelaEditoras.zeraCampos();
                }
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
    public static void main(String args[]) {

        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaEditora().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbImagem1;
    private javax.swing.JLabel lbImagem2;
    private javax.swing.JLabel lbImagem3;
    private javax.swing.JLabel lbNome1;
    private javax.swing.JLabel lbNome2;
    private javax.swing.JLabel lbNome3;
    // End of variables declaration//GEN-END:variables
}

/*int id = editora.busca(editora.buscador("Editora"));
        if (id == -1) {
            editora.informativo("Nenhuma editora possui este número de identificação!!!");
        } else {
            editora.exclui(id); janelaEditoras.zeraCampos();
            editora.mensagens(3);
            editora.getEditoraAtual().setIdEditora(1);
        }*/

    /*if (editora.busca(editora.buscador("Editora")) == -1) {
            editora.informativo("Nenhuma editora possui este número de identificação!!!");
        } else {
            janelaEditoras.setCampos(); editora.setValidar(3);
            
        }*/

/*janelaEditoras.setPos(editora.busca(editora.buscador("Editora"))); 
        if (janelaEditoras.getPos() == -1) {
            editora.informativo("Nenhuma editora possui este número de identificação!!!");
        } else {
            janelaEditoras.setCampos(); editora.setValidar(2);
             
        }*/

/*editora.setValidar(1);*/