/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.QuadrinhoDAO;

/**
 *
 * @author willi
 */
public class JanelaQuadrinho extends javax.swing.JFrame {

    private QuadrinhoDAO HQ = QuadrinhoDAO.getDaoQuadrinho();
    private final JanelaQuadrinhos janelaQuadrinhos = JanelaQuadrinhos.getJanelaQuadrinho();

    private static JanelaQuadrinho janelaQuadrinho;
    private JanelaQuadrinho () {
        initComponents ();
        HQ.getConBD().inicializaTudo ("planetaHulk.jpg", "Planeta Hulk", lbImagem1, lbNome1);
        HQ.getConBD().inicializaTudo ("flashPoint.jpg", "FlashPoint", lbImagem2, lbNome2);
        HQ.getConBD().inicializaTudo ("PiadaMortal.jpg", "Piada Mortal", lbImagem3, lbNome3);
        HQ.getConBD().inicializaTudo ("theBoys.jpg", "The Boys", lbImagem4, lbNome4);
    }
    public final static JanelaQuadrinho getJanelaQuadrinho () {
        if (janelaQuadrinho == null) {
            janelaQuadrinho = new JanelaQuadrinho ();
        }
        return janelaQuadrinho;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbImagem2 = new javax.swing.JLabel();
        lbImagem4 = new javax.swing.JLabel();
        lbImagem1 = new javax.swing.JLabel();
        lbImagem3 = new javax.swing.JLabel();
        lbNome1 = new javax.swing.JLabel();
        lbNome3 = new javax.swing.JLabel();
        lbNome2 = new javax.swing.JLabel();
        lbNome4 = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lbTitulo.setText("Quadrinhos ");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel2.setText("Alguns dos quadrinhos mais importantes");

        lbImagem2.setText("Imagem 2");

        lbImagem4.setText("Imagem 4");

        lbImagem1.setText("Imagem 1");

        lbImagem3.setText("Imagem 3");

        lbNome1.setText("Nome 1");

        lbNome3.setText("Nome 3");

        lbNome2.setText("Nome 2");

        lbNome4.setText("Nome 4");

        btAdicionar.setText("Adicionar Quadrinho");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btEditar.setText("Editar Quadrinho");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btBuscar.setText("Buscar Quadrinho");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir Quadrinho");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbImagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(lbNome1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btAdicionar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(lbNome2)
                                .addGap(144, 144, 144)
                                .addComponent(lbNome3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(btEditar)
                                .addGap(68, 68, 68)
                                .addComponent(btBuscar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImagem4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lbNome4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btExcluir)
                        .addGap(30, 30, 30)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbTitulo)
                        .addGap(332, 332, 332))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(267, 267, 267))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImagem4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome1)
                    .addComponent(lbNome2)
                    .addComponent(lbNome3)
                    .addComponent(lbNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btEditar)
                    .addComponent(btBuscar)
                    .addComponent(btExcluir))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        if (HQ.getConBD().verificaConexao()) {
            JanelaInicial.criaThread(janelaQuadrinhos); janelaQuadrinhos.zerarCampos();
            HQ.getConBD().setValidar(1); janelaQuadrinhos.inserirCombos(0);
        }    
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        if (HQ.getConBD().verificaConexao()) {
            janelaQuadrinhos.setPos(HQ.getConBD().buscador("Autor"));
            if (janelaQuadrinhos.getPos() < 1) {
                HQ.getConBD().informativo("Nenhum autor possui este número de identificação!!!");
            } else {
                if (HQ.buscar(janelaQuadrinhos.getPos())) {
                    janelaQuadrinhos.inserirCombos(1);
                    janelaQuadrinhos.setCampos(janelaQuadrinhos.getPos());
                    HQ.getConBD().setValidar(2);
                    JanelaInicial.criaThread(janelaQuadrinhos);
                }
            }
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        if (HQ.getConBD().verificaConexao()) {
            int id = HQ.getConBD().buscador("Quadrinho");
            if (id < 1) {
                HQ.getConBD().informativo("Nenhum Quadrinho possui este número de identificação!!!");
            } else {
                if (HQ.buscar(id)) {
                    janelaQuadrinhos.esvaziarCombos(2);
                    janelaQuadrinhos.setCampos(id);
                    HQ.getConBD().setValidar(3);
                    JanelaInicial.criaThread(janelaQuadrinhos);
                }
            }
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (HQ.getConBD().verificaConexao()) {
            int id = HQ.getConBD().buscador("Quadrinho");
            if (id < 1) {
                HQ.getConBD().informativo("Nenhum quadrinho possui este número de identificação!!!");
            } else {
                if (HQ.excluir(id)) {
                    HQ.getConBD().mensagens(3); janelaQuadrinhos.esvaziarCombos(0);
                    janelaQuadrinhos.zerarCampos();
                }
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaQuadrinho().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbImagem1;
    private javax.swing.JLabel lbImagem2;
    private javax.swing.JLabel lbImagem3;
    private javax.swing.JLabel lbImagem4;
    private javax.swing.JLabel lbNome1;
    private javax.swing.JLabel lbNome2;
    private javax.swing.JLabel lbNome3;
    private javax.swing.JLabel lbNome4;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}