/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;
import DAO.ControllerArquivo;
import DAO.DAO;
import Relatorios.ControleRelatorios;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JFrame;
/**
 *
 * @author willi
 */
public final class JanelaInicial extends javax.swing.JFrame {
    
    private final ControleRelatorios forRelatorios = ControleRelatorios.getcRelatorios();
    private static JanelaInicial janelaInicial = null;
    private final DAO bancoDados = DAO.getDao();
    private final ControllerArquivo arqBanco = new ControllerArquivo();

    /**
     * Creates new form JanelaInicial
     */
    private JanelaInicial() {
        initComponents();
        inciaComImagens();
    }
    
    public final void inciaComImagens () {
        bancoDados.alteraImagens ("marvelVSdc.jpg", lbImagem);
        bancoDados.alteraImagens ("stanlee.png", lbImagem2);
        bancoDados.alteraImagens ("jackkirby.jfif", lbImagem3);
    }

    public static JanelaInicial getJanelaIncioal () {
        if (janelaInicial == null) {
            janelaInicial = new JanelaInicial ();
            janelaInicial.situacaoConexao();
        }
        return janelaInicial;
    }

    public final boolean situacaoConexao () {
        if (janelaInicial.bancoDados.getConexao() == null){
            janelaInicial.btConectaBD.setBackground(Color.red);
            janelaInicial.btConectaBD.setText("Desconectado");
            janelaInicial.btConectaBD.setForeground(Color.black);
            return false;
        } else {
            janelaInicial.btConectaBD.setBackground(Color.GREEN);
            janelaInicial.btConectaBD.setText("Conectado");
            janelaInicial.btConectaBD.setForeground(Color.white);
            return true;
        }
    }
    
/*
    Utiliza o conceito de Classe Interna Anônima para criar várias threads.
    O parâmetro JFrame corresponde a janela que será manipulada.
    É um método estático para que as outras classes tenham acesso sem a necessidade
    de se instanciar um novo objeto.
*/
    public final static void criaThread (JFrame janela) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                janela.setVisible(true);
            }
        });
    }
    
    public static void altDadosConn (String url, String user, String senha) throws SQLException {
        janelaInicial.bancoDados.initAtributos(url, user, senha);
        janelaInicial.situacaoConexao();
    }
    
    public void conectarBD () {
        try {
            if (bancoDados.ArquivoVazio()) {
                criaThread(CadastrarBD.getJanelaCadBD());
                btConectaBD.setSelected(false);
            } else {
                bancoDados.realizaConexao(btConectaBD.isSelected());
                if (bancoDados.verificaConexao()) {
                    bancoDados.getConexao().setAutoCommit(false);
                }
                situacaoConexao();
            } 
        } catch (SQLException sql) {
            bancoDados.errosSQL("Erro ao realizar conexão:", sql);
            btConectaBD.setSelected(false);
        } 
    }
    
    public void desconectarBD () {
        try {
            bancoDados.getConexao().close();
            bancoDados.realizaConexao(btConectaBD.isSelected());
        } catch (SQLException ex) {
            bancoDados.errosSQL("Erro ao fechar a conexão!!", ex);
        } finally {
            janelaInicial.situacaoConexao();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbImagem = new javax.swing.JLabel();
        btEscritor = new javax.swing.JButton();
        btQuadrinhos = new javax.swing.JButton();
        btEditora = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbImagem2 = new javax.swing.JLabel();
        lbImagem3 = new javax.swing.JLabel();
        btConectaBD = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbRelatorios = new javax.swing.JMenu();
        rQuadrinhos = new javax.swing.JMenuItem();
        rEscritores = new javax.swing.JMenuItem();
        rEditoras = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        jLabel1.setText("Katholikós Kómiks");

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel2.setText("A sua Loja de Quadrinhos");

        lbImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btEscritor.setText("Autores");
        btEscritor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEscritorActionPerformed(evt);
            }
        });

        btQuadrinhos.setText("Quadrinhos");
        btQuadrinhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuadrinhosActionPerformed(evt);
            }
        });

        btEditora.setText("Editora");
        btEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditoraActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel3.setText("Selecione a Aba em que deseja acessar:");

        lbImagem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbImagem3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btConectaBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConectaBDActionPerformed(evt);
            }
        });

        jLabel4.setText("Situação do Banco de Dados:");

        mbRelatorios.setText("Gerar Relatórios");
        mbRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mbRelatoriosMouseClicked(evt);
            }
        });

        rQuadrinhos.setText("Relatório - Quadrinhos");
        rQuadrinhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rQuadrinhosActionPerformed(evt);
            }
        });
        mbRelatorios.add(rQuadrinhos);

        rEscritores.setText("Relatório - Escritores e Desenhistas");
        rEscritores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rEscritoresActionPerformed(evt);
            }
        });
        mbRelatorios.add(rEscritores);

        rEditoras.setText("Relatório - Editoras");
        rEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rEditorasActionPerformed(evt);
            }
        });
        mbRelatorios.add(rEditoras);

        jMenuItem1.setText("Relatório - Editoras a partir de Data de Fundação ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mbRelatorios.add(jMenuItem1);

        jMenuBar1.add(mbRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbImagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(203, 203, 203))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btEditora)
                                .addGap(155, 155, 155)
                                .addComponent(btEscritor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(12, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btQuadrinhos)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConectaBD, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConectaBD, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQuadrinhos)
                    .addComponent(btEditora)
                    .addComponent(btEscritor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btEscritorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEscritorActionPerformed
        criaThread(JanelaEscritor.getJanelaEscritor(false));
        JanelaEscritor.getJanelaEscritor(true);
    }//GEN-LAST:event_btEscritorActionPerformed

    private void btEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditoraActionPerformed
        criaThread(JanelaEditora.getJanelaEditora());
    }//GEN-LAST:event_btEditoraActionPerformed

    private void btQuadrinhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuadrinhosActionPerformed
        criaThread(JanelaQuadrinho.getJanelaQuadrinho());
    }//GEN-LAST:event_btQuadrinhosActionPerformed

    private void btConectaBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConectaBDActionPerformed
        if (btConectaBD.isSelected()) {
            conectarBD();
        } else {
            desconectarBD ();
        }
    }//GEN-LAST:event_btConectaBDActionPerformed

    private void mbRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mbRelatoriosMouseClicked
        if (bancoDados.verificaConexao()) {
            mbRelatorios.setSelected(false);
        }
    }//GEN-LAST:event_mbRelatoriosMouseClicked

    private void rQuadrinhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rQuadrinhosActionPerformed
        forRelatorios.Relatorios(forRelatorios.file_relatorio_quadrinho, forRelatorios.relatorio_quadrinho_pdf, null);
    }//GEN-LAST:event_rQuadrinhosActionPerformed

    private void rEscritoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rEscritoresActionPerformed
        forRelatorios.Relatorios(forRelatorios.file_relatorio_escritorDesenhista, forRelatorios.relatorio_escritorDesenhista_pdf, null);
    }//GEN-LAST:event_rEscritoresActionPerformed

    private void rEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rEditorasActionPerformed
        forRelatorios.Relatorios(forRelatorios.file_relatorio_editora, forRelatorios.relatorio_editora_pdf, null);
    }//GEN-LAST:event_rEditorasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        forRelatorios.Relatorios(forRelatorios.file_parametro_editora, forRelatorios.relatorio_parametro_editora_pdf, forRelatorios.criaParametros());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaInicial.getJanelaIncioal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btConectaBD;
    private javax.swing.JButton btEditora;
    private javax.swing.JButton btEscritor;
    private javax.swing.JButton btQuadrinhos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JLabel lbImagem2;
    private javax.swing.JLabel lbImagem3;
    private javax.swing.JMenu mbRelatorios;
    private javax.swing.JMenuItem rEditoras;
    private javax.swing.JMenuItem rEscritores;
    private javax.swing.JMenuItem rQuadrinhos;
    // End of variables declaration//GEN-END:variables
}
