/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.EditoraDAO;
import java.sql.SQLException;

/**
 *
 * @author willi
 */
public class JanelaEditoras extends javax.swing.JFrame {
    
    private final EditoraDAO conEditora = EditoraDAO.getDaoEditora();
    private static JanelaEditoras janelaEditora;
    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
    
    
    /**
     * Creates new form JanelaEditora1
     */
    private JanelaEditoras() {
        initComponents();
        cxNome.requestFocus();
    }
    
    public static JanelaEditoras getJanelaCadEditora () {
        if (janelaEditora == null) {
            janelaEditora = new JanelaEditoras ();
        }
        return janelaEditora;
    }
    
    public final boolean preencherEditora () {
        try {
            conEditora.getEditora().setNome(cxNome.getText());
            conEditora.getEditora().setFundador(cxFundador.getText());
            conEditora.getEditora().setPresidente(cxPresidente.getText());
            conEditora.getEditora().setSede(cxSede.getText());
            conEditora.getEditora().setAnoFund(Integer.parseInt(cxAnoFund.getText()));
            conEditora.getEditora().setSituacao(rbAtiva.isSelected());
            conEditora.getEditora().setWebsite(cxWebsite.getText());
            return true;
        } catch (NumberFormatException num){
            conEditora.getConBD().informativo("Ano de fundação deve ser número");
            return false;
        }
    }
    
    public void setCampos (int id) {
        try {
            conEditora.getConBD().setConjuntos(conEditora.getConBD().getConexao().createStatement(1005,1008).executeQuery("SELECT * FROM editora WHERE ed_id = "+id+";"));
            if (conEditora.getConBD().getConjuntos().first()) {
                cxNome.setText(conEditora.getConBD().getConjuntos().getString("ed_nome"));
                cxFundador.setText(conEditora.getConBD().getConjuntos().getString("ed_fundador"));
                cxPresidente.setText(conEditora.getConBD().getConjuntos().getString("ed_presidente"));
                cxSede.setText(conEditora.getConBD().getConjuntos().getString("ed_sede"));
                cxAnoFund.setText(conEditora.getConBD().getConjuntos().getString("ed_anoFund"));
                cxWebsite.setText(conEditora.getConBD().getConjuntos().getString("ed_website"));
                rbAtiva.setSelected(conEditora.getConBD().getConjuntos().getString("ed_situacao").equals("ATIVA"));
                rbDesativada.setSelected(!rbAtiva.isSelected());
                conEditora.getEditora().setId(conEditora.getConBD().getConjuntos().getInt("ed_id"));
                preencherEditora();
                conEditora.getConBD().getConjuntos().close();
            }
        } catch (SQLException ex) {
            conEditora.getConBD().errosSQL("Não foi possível alterar os campos com as informações do banco de dados", ex);
        }
    }
    
    public void zeraCampos () {
        cxNome.setText("");
        cxFundador.setText("");
        cxSede.setText("");
        cxPresidente.setText("");
        cxWebsite.setText("");
        cxAnoFund.setText("");
        rbAtiva.setSelected(false);
        rbDesativada.setSelected(rbAtiva.isSelected());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grSituacao = new javax.swing.ButtonGroup();
        lbPresidente = new javax.swing.JLabel();
        cxFundador = new javax.swing.JTextField();
        cxPresidente = new javax.swing.JTextField();
        lbFundador = new javax.swing.JLabel();
        cxSede = new javax.swing.JTextField();
        lbSede = new javax.swing.JLabel();
        cxAnoFund = new javax.swing.JTextField();
        lbAnoFund = new javax.swing.JLabel();
        rbAtiva = new javax.swing.JRadioButton();
        rbDesativada = new javax.swing.JRadioButton();
        lbSituacao = new javax.swing.JLabel();
        cxWebsite = new javax.swing.JTextField();
        lbTitulo = new javax.swing.JLabel();
        lbsalvar = new javax.swing.JButton();
        lbWebsite = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbPresidente.setText("Presidente da Editora");

        lbFundador.setText("Fundador da Editora");

        lbSede.setText("Localidade da Sede");

        lbAnoFund.setText("Ano de Fundação");

        grSituacao.add(rbAtiva);
        rbAtiva.setText("Ativa");

        grSituacao.add(rbDesativada);
        rbDesativada.setText("Desativada");

        lbSituacao.setText("Situação");

        lbTitulo.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lbTitulo.setText("Informações da Editora");

        lbsalvar.setText("Salvar");
        lbsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbsalvarActionPerformed(evt);
            }
        });

        lbWebsite.setText("Website");

        jLabel1.setText("Nome da Editora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbWebsite)
                                    .addComponent(cxAnoFund))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lbAnoFund)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbDesativada, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbAtiva, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbSituacao)
                                .addGap(33, 33, 33)))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cxNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxWebsite)
                            .addComponent(cxSede)
                            .addComponent(cxPresidente)
                            .addComponent(cxFundador))
                        .addGap(49, 49, 49))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lbsalvar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lbPresidente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lbFundador))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lbSede)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFundador)
                .addGap(10, 10, 10)
                .addComponent(cxFundador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPresidente)
                .addGap(11, 11, 11)
                .addComponent(cxPresidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSede)
                .addGap(12, 12, 12)
                .addComponent(cxSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbSituacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbAtiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbDesativada))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbAnoFund)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxAnoFund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbWebsite)))
                .addGap(10, 10, 10)
                .addComponent(cxWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lbsalvar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbsalvarActionPerformed
        switch (conEditora.getConBD().getValidar()) {
        case 1:
            if (preencherEditora()) {
                if (conEditora.inserir()) {
                    conEditora.getConBD().mensagens(conEditora.getConBD().getValidar());
                }
            }
            break;
        case 2:
            if (preencherEditora()) {
                if (conEditora.editar(id)) {
                   conEditora.getConBD().mensagens(conEditora.getConBD().getValidar()); 
                }
            }
            break;
        case 3:
            lbsalvar.enableInputMethods(false);
            break;
    }
        this.dispose(); zeraCampos();
    }//GEN-LAST:event_lbsalvarActionPerformed

    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaEditoras().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cxAnoFund;
    private javax.swing.JTextField cxFundador;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxPresidente;
    private javax.swing.JTextField cxSede;
    private javax.swing.JTextField cxWebsite;
    private javax.swing.ButtonGroup grSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAnoFund;
    private javax.swing.JLabel lbFundador;
    private javax.swing.JLabel lbPresidente;
    private javax.swing.JLabel lbSede;
    private javax.swing.JLabel lbSituacao;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbWebsite;
    private javax.swing.JButton lbsalvar;
    private javax.swing.JRadioButton rbAtiva;
    private javax.swing.JRadioButton rbDesativada;
    // End of variables declaration//GEN-END:variables
}
