name: Actions nos ambiente-Desenvolvimento

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 9,15,21 5,6,15,16 1,4,7,10,12 *'
    
jobs:
  development:
    runs-on: ubuntu-latest
    environment:
      name: Desenvolvimento
    steps:
      - name: Realiza uma Action no ambiente-Desenvolvimento
        run: echo Estou no ambiente de Desenvolvimento!!!
        
  production:
    runs-on: ubuntu-latest
    environment:
      name: Produção
      url: 'http://curiosamentegigante.orgfree.com/SONY.html'
    needs: development
    steps:
      - name: Realiza uma Action no ambiente-Produção. Acessa um site criado por mim, com o intuito de aprender!
        run: echo Estou no ambiente de Produção!!!
